Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/cforge_env/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## filter out non country rows
wealth_18 = wealth[(wealth['year'] == 2018) & (wealth['continent'].isin(['Asia','Europe','Africa','North America','Oceania','South America']))]
## calculate gdp per capita
wealth_18['gdp_per_capita'] = wealth_18['gdp']/wealth_18['population']
wealth_18['share_global_co2'] = wealth_18['share_global_co2']
## remove rows with missing values
wealth_18 = wealth_18[(wealth_18['gdp']!=0) & (wealth_18['share_global_co2']!=0)]

fig = px.scatter(wealth_18, x="gdp_per_capita", y="co2_per_capita",
	         size="population", color = 'continent',
                 hover_name="country", log_x=True, log_y=True, size_max=60,trendline='ols',trendline_scope="overall", title = 'CO2 per capita vs GDP per capita')
fig.update_layout(
    xaxis_title="GDP per capita ($)",
    yaxis_title="CO2 per capita (t)"
)
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/wv/j_lqm8yn4ndb1hvhthjcrb540000gn/T/ipykernel_20548/3411770185.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m## filter out non country rows[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mwealth_18[0m [0;34m=[0m [0mwealth[0m[0;34m[[0m[0;34m([0m[0mwealth[0m[0;34m[[0m[0;34m'year'[0m[0;34m][0m [0;34m==[0m [0;36m2018[0m[0;34m)[0m [0;34m&[0m [0;34m([0m[0mwealth[0m[0;34m[[0m[0;34m'continent'[0m[0;34m][0m[0;34m.[0m[0misin[0m[0;34m([0m[0;34m[[0m[0;34m'Asia'[0m[0;34m,[0m[0;34m'Europe'[0m[0;34m,[0m[0;34m'Africa'[0m[0;34m,[0m[0;34m'North America'[0m[0;34m,[0m[0;34m'Oceania'[0m[0;34m,[0m[0;34m'South America'[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;31m## calculate gdp per capita[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mwealth_18[0m[0;34m[[0m[0;34m'gdp_per_capita'[0m[0;34m][0m [0;34m=[0m [0mwealth_18[0m[0;34m[[0m[0;34m'gdp'[0m[0;34m][0m[0;34m/[0m[0mwealth_18[0m[0;34m[[0m[0;34m'population'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mwealth_18[0m[0;34m[[0m[0;34m'share_global_co2'[0m[0;34m][0m [0;34m=[0m [0mwealth_18[0m[0;34m[[0m[0;34m'share_global_co2'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'wealth' is not defined
NameError: name 'wealth' is not defined

